logging:
  level:
    fr:
      sncf:
        d2d:
          serversideapp: DEBUG
spring:
  devtools:
    restart:
      exclude: ""
  datasource:
    url: jdbc:h2:file:${java.io.tmpdir}/database-test-app
    username: sa
    password: password
    driverClassName: org.h2.Driver
  liquibase:
    change-log: classpath:/database/changelog.xml